# This is the docker setup for the 'local' environment

version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    volumes:
      - database:/mysql
    environment:
     MYSQL_ROOT_PASSWORD: Fy+0nEciFa4o

volumes:
  database: 