# This is the docker setup for the 'local' environment

version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  dynamodb-local:
    container_name: dynamodb-local
    image: "amazon/dynamodb-local"
    networks:
      - local-dynamodb
    ports:
      - "8000:8000" 
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"   
    working_dir: /home/dynamodblocal 
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"

networks:
  local-dynamodb:
    name: local-dynamodb

volumes:
  database: 